<?php

use PhpCsFixer\{Config, Finder};

return (new Config())->setRules([
  // '@PSR1'                                    => true,
  // '@PSR2'                                    => true,
  // '@PSR12'                                   => true,
  'align_multiline_comment'                  => ['comment_type' => 'all_multiline'],
  'array_indentation'                        => true,
  'array_syntax'                             => ['syntax' => 'short'],
  'assign_null_coalescing_to_coalesce_equal' => true,
  'backtick_to_shell_exec'                   => true,
  'binary_operator_spaces'                   => ['default' => 'align_single_space_minimal'],
  'blank_line_after_opening_tag'             => true,
  'blank_line_after_namespace'               => true,
  'blank_line_before_statement'              => ['statements' => [
    'declare',
    'return',
    'throw',
    'try',
    'phpdoc',
    'default',
    'exit',
    'goto',
  ]],
  'blank_line_between_import_groups' => true,
  'braces'                           => [
    'allow_single_line_anonymous_class_with_empty_body' => true,
    'allow_single_line_closure'                         => true,
    'position_after_control_structures'                 => 'same',
    'position_after_functions_and_oop_constructs'       => 'next',
    'position_after_anonymous_constructs'               => 'same',
  ],
  'cast_spaces'                 => ['space' => 'single'],
  'class_attributes_separation' => ['elements' => [
    'const'        => 'only_if_meta',
    'method'       => 'one',
    'property'     => 'none',
    'trait_import' => 'none',
    'case'         => 'only_if_meta',
  ]],
  'class_definition' => [
    'single_line'                  => true,
    'single_item_single_line'      => true,
    'space_before_parenthesis'     => true,
    'inline_constructor_arguments' => true,
  ],
  'class_reference_name_casing'             => true,
  'clean_namespace'                         => true,
  'combine_consecutive_issets'              => true,
  'combine_consecutive_unsets'              => true,
  'compact_nullable_typehint'               => true,
  'concat_space'                            => ['spacing' => 'one'],
  'constant_case'                           => ['case' => 'lower'],
  'control_structure_braces'                => true,
  'control_structure_continuation_position' => ['position' => 'same_line'],
  'curly_braces_position'                   => [
    'control_structures_opening_brace'          => 'same_line',
    'functions_opening_brace'                   => 'next_line_unless_newline_at_signature_end',
    'anonymous_functions_opening_brace'         => 'same_line',
    'classes_opening_brace'                     => 'next_line_unless_newline_at_signature_end',
    'anonymous_classes_opening_brace'           => 'same_line',
    'allow_single_line_empty_anonymous_classes' => true,
    'allow_single_line_anonymous_functions'     => true,
  ],
  'declare_equal_normalize'      => true,
  'dir_constant'                 => true,
  'declare_parentheses'          => true,
  'echo_tag_syntax'              => true,
  'elseif'                       => true,
  'empty_loop_body'              => ['style' => 'braces'],
  'empty_loop_condition'         => ['style' => 'while'],
  'encoding'                     => true,
  'escape_implicit_backslashes'  => true,
  'explicit_indirect_variable'   => true,
  'explicit_string_variable'     => true,
  'full_opening_tag'             => true,
  'fully_qualified_strict_types' => true,
  'function_declaration'         => [
    'closure_function_spacing'   => 'none',
    'closure_fn_spacing'         => 'none',
    'trailing_comma_single_line' => false,
  ],
  'function_typehint_space'   => true,
  'general_phpdoc_tag_rename' => true,
  'global_namespace_import'   => [
    'import_classes'   => true,
    'import_constants' => null,
    'import_functions' => null,
  ],
  'heredoc_to_nowdoc'           => true,
  'include'                     => true,
  'increment_style'             => ['style' => 'post'],
  'indentation_type'            => true,
  'integer_literal_case'        => true,
  'lambda_not_used_import'      => true,
  'logical_operators'           => true,
  'heredoc_indentation'         => ['indentation' => 'same_as_start'],
  'line_ending'                 => true,
  'linebreak_after_opening_tag' => true,
  'list_syntax'                 => ['syntax' => 'short'],
  'lowercase_cast'              => true,
  'lowercase_keywords'          => true,
  'modernize_types_casting'     => true,
  'lowercase_static_reference'  => true,
  'magic_constant_casing'       => true,
  'magic_method_casing'         => true,
  'method_argument_space'       => [
    'after_heredoc'                    => true,
    'on_multiline'                     => 'ensure_fully_multiline',
    'keep_multiple_spaces_after_comma' => false,
  ],
  'method_chaining_indentation'             => true,
  'multiline_comment_opening_closing'       => true,
  'multiline_whitespace_before_semicolons'  => ['strategy' => 'no_multi_line'],
  'native_function_casing'                  => true,
  'native_function_type_declaration_casing' => true,
  'new_with_braces'                         => ['named_class' => true, 'anonymous_class' => false],
  'pow_to_exponentiation'                   => true,
  'no_alias_functions'                      => ['sets' => ['@all']],
  'no_alias_language_construct_call'        => true,
  'no_alternative_syntax'                   => true,
  'no_break_comment'                        => true,
  'no_binary_string'                        => true,
  'no_blank_lines_after_class_opening'      => true,
  'no_blank_lines_after_phpdoc'             => true,
  'no_closing_tag'                          => true,
  'no_empty_comment'                        => true,
  'no_empty_phpdoc'                         => true,
  'no_empty_statement'                      => true,
  'no_extra_blank_lines'                    => ['tokens' => [
    'attribute',
    'curly_brace_block',
    'default',
    'extra',
    'parenthesis_brace_block',
    'square_brace_block',
    'return',
    'switch',
    'throw',
    'use',
    'use_trait',
  ]],
  'no_leading_import_slash'                          => true,
  'no_leading_namespace_whitespace'                  => true,
  'no_mixed_echo_print'                              => ['use' => 'echo'],
  'no_multiple_statements_per_line'                  => true,
  'no_multiline_whitespace_around_double_arrow'      => true,
  'no_null_property_initialization'                  => true,
  'no_useless_nullsafe_operator'                     => true,
  'no_short_bool_cast'                               => true,
  'no_singleline_whitespace_before_semicolons'       => true,
  'no_spaces_after_function_name'                    => true,
  'no_useless_concat_operator'                       => true,
  'no_space_around_double_colon'                     => true,
  'no_spaces_around_offset'                          => true,
  'no_spaces_inside_parenthesis'                     => true,
  'no_useless_sprintf'                               => true,
  'no_superfluous_elseif'                            => true,
  'no_superfluous_phpdoc_tags'                       => ['allow_mixed' => true, 'allow_unused_params' => true],
  'no_trailing_comma_in_list_call'                   => true,
  'no_trailing_comma_in_singleline_array'            => true,
  'no_trailing_comma_in_singleline_function_call'    => true,
  'no_trailing_comma_in_singleline'                  => ['elements' => ['arguments', 'array', 'array_destructuring', 'group_import']],
  'group_import'                                     => true,
  'no_trailing_whitespace_in_comment'                => true,
  'no_unneeded_control_parentheses'                  => true,
  'no_unneeded_curly_braces'                         => true,
  'no_unreachable_default_argument_value'            => true,
  'no_unneeded_import_alias'                         => true,
  'no_unset_cast'                                    => true,
  'no_unused_imports'                                => true,
  'no_useless_else'                                  => true,
  'no_useless_return'                                => true,
  'no_whitespace_before_comma_in_array'              => true,
  'no_whitespace_in_blank_line'                      => true,
  'normalize_index_brace'                            => true,
  'not_operator_with_successor_space'                => true,
  'nullable_type_declaration_for_default_null_value' => true,
  'object_operator_without_whitespace'               => true,
  'octal_notation'                                   => true,
  'operator_linebreak'                               => true,
  'ordered_class_elements'                           => ['order' => [
    'use_trait',
    'public',
    'protected',
    'private',
    'constant',
    'constant_public',
    'constant_protected',
    'constant_private',
    'property',
    'property_static',
    'property_public_static',
    'property_protected_static',
    'property_private_static',
    'property_public_readonly',
    'property_protected_readonly',
    'property_private_readonly',
    'property_public',
    'property_protected',
    'property_private',
    'construct',
    'destruct',
    'magic',
    'method',
    'method_abstract',
    'method_public_abstract_static',
    'method_protected_abstract_static',
    'method_public_abstract',
    'method_protected_abstract',
    'method_public_static',
    'method_static',
    'method_protected_static',
    'method_private_static',
    'method_public',
    'method_protected',
    'method_private',
    'phpunit',
  ]],
  'ordered_imports'                               => ['imports_order' => ['class', 'function', 'const'], 'sort_algorithm' => 'length'],
  'phpdoc_add_missing_param_annotation'           => ['only_untyped' => true],
  'phpdoc_align'                                  => true,
  'phpdoc_annotation_without_dot'                 => true,
  'phpdoc_indent'                                 => true,
  'phpdoc_inline_tag_normalizer'                  => true,
  'phpdoc_line_span'                              => ['const' => 'single', 'property' => 'single', 'method' => 'multi'],
  'phpdoc_no_access'                              => true,
  'phpdoc_no_alias_tag'                           => true,
  'phpdoc_no_empty_return'                        => true,
  'phpdoc_no_package'                             => true,
  'phpdoc_no_useless_inheritdoc'                  => true,
  'phpdoc_order'                                  => true,
  'phpdoc_return_self_reference'                  => true,
  'phpdoc_scalar'                                 => true,
  'phpdoc_separation'                             => true,
  'phpdoc_single_line_var_spacing'                => true,
  'phpdoc_summary'                                => true,
  'phpdoc_tag_casing'                             => true,
  'phpdoc_tag_type'                               => true,
  'phpdoc_to_comment'                             => true,
  'string_length_to_empty'                        => true,
  'phpdoc_trim'                                   => true,
  'phpdoc_trim_consecutive_blank_line_separation' => true,
  'phpdoc_types'                                  => true,
  'phpdoc_types_order'                            => ['null_adjustment' => 'always_last'],
  'phpdoc_var_annotation_correct_order'           => true,
  'phpdoc_var_without_name'                       => true,
  'return_assignment'                             => true,
  'return_type_declaration'                       => true,
  'self_static_accessor'                          => true,
  'semicolon_after_instruction'                   => true,
  'short_scalar_cast'                             => true,
  'simple_to_complex_string_variable'             => true,
  'simplified_if_return'                          => true,
  'simplified_null_return'                        => true,
  'single_blank_line_before_namespace'            => true,
  'single_class_element_per_statement'            => ['elements' => ['const', 'property']],
  'single_blank_line_at_eof'                      => true,
  'single_import_per_statement'                   => false,
  'single_line_comment_style'                     => true,
  'single_line_comment_spacing'                   => true,
  'single_line_after_imports'                     => true,
  // 'single_line_empty_body'                        => false,
  'single_line_throw'                 => true,
  'single_quote'                      => true,
  'single_space_after_construct'      => true,
  'single_trait_insert_per_statement' => true,
  'space_after_semicolon'             => ['remove_in_empty_for_expressions' => true],
  'standardize_increment'             => true,
  'standardize_not_equals'            => true,
  'function_to_constant'              => true,
  'statement_indentation'             => true,
  'switch_case_semicolon_to_colon'    => true,
  'switch_case_space'                 => true,
  'no_unset_on_property'              => true,
  'is_null'                           => true,
  'switch_continue_to_break'          => true,
  'get_class_to_class_keyword'        => true,
  'ternary_operator_spaces'           => true,
  'ternary_to_null_coalescing'        => true,
  'set_type_to_cast'                  => true,
  'combine_nested_dirname'            => true,
  'trailing_comma_in_multiline'       => ['after_heredoc' => true],
  'trim_array_spaces'                 => true,
  'types_spaces'                      => ['space' => 'none', 'space_multiple_catch' => 'none'],
  'unary_operator_spaces'             => true,
  'visibility_required'               => ['elements' => ['property', 'method', 'const']],
  'whitespace_after_comma_in_array'   => ['ensure_single_space' => true],
  'yoda_style'                        => ['always_move_variable' => false, 'equal' => false, 'identical' => false, 'less_and_greater' => false],
])->setLineEnding("\n")->setIndent('  ')->setFinder(Finder::create()->in(__DIR__));
